name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update chapter navigation
        run: |
          for dir in novels/*/; do
            novel_name=$(basename "$dir")
            python scripts/chaplink.py "$novel_name"
          done

      - name: Update posts.js
        run: python scripts/blog.py

      - name: Generate novels.html
        run: python scripts/novels.py

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_FOLDER }}
          security: loose
          exclude: |
            .git*
            .git*/**
            .github/**
            .gitignore
            .ftpignore
            README.md
            *.md
            node_modules/**
            *.py
          dangerous-clean-slate: false
